In [44]:
from datapipeline import DataFeed

In [45]:
self = DataFeed()

In [47]:
self.get_g20_cpi

              G20CPI
Date
2019-01-01  3.574385
2019-02-01  3.574385
2019-03-01  3.574385
2019-04-01  3.574385
2019-05-01  3.574385
2019-06-01  3.574385
2019-07-01  3.574385
2019-08-01  3.574385
2019-09-01  3.574385
2019-10-01  3.574385
2019-11-01  3.574385
2019-12-01  3.574385
2020-01-01  2.707257
2020-02-01  2.707257
2020-03-01  2.707257
2020-04-01  2.707257
2020-05-01  2.707257
2020-06-01  2.707257
2020-07-01  2.707257
2020-08-01  2.707257
2020-09-01  2.707257
2020-10-01  2.707257
2020-11-01  2.707257
2020-12-01  2.707257
2021-01-01  4.290450
2021-02-01  4.290450
2021-03-01  4.290450
2021-04-01  4.290450
2021-05-01  4.290450
2021-06-01  4.290450
2021-07-01  4.290450
2021-08-01  4.470521
2021-09-01  4.614241
2021-10-01  5.224842
2021-11-01  5.851680
2021-12-01  6.145003
2022-01-01  6.486124
2022-02-01  6.801695
2022-03-01  7.900509
2022-04-01  8.518237
2022-05-01  8.855436
2022-06-01  9.249396
2022-07-01       NaN

In [2]:
import os

In [42]:
file_name = "DataFeeds/G20CPI.xlsx"
df = pd.read_excel(file_name,index_col=0,parse_dates=True)

In [43]:
df

              G20CPI
Date
2019-01-01  3.574385
2019-02-01  3.574385
2019-03-01  3.574385
2019-04-01  3.574385
2019-05-01  3.574385
2019-06-01  3.574385
2019-07-01  3.574385
2019-08-01  3.574385
2019-09-01  3.574385
2019-10-01  3.574385
2019-11-01  3.574385
2019-12-01  3.574385
2020-01-01  2.707257
2020-02-01  2.707257
2020-03-01  2.707257
2020-04-01  2.707257
2020-05-01  2.707257
2020-06-01  2.707257
2020-07-01  2.707257
2020-08-01  2.707257
2020-09-01  2.707257
2020-10-01  2.707257
2020-11-01  2.707257
2020-12-01  2.707257
2021-01-01  4.290450
2021-02-01  4.290450
2021-03-01  4.290450
2021-04-01  4.290450
2021-05-01  4.290450
2021-06-01  4.290450
2021-07-01  4.290450
2021-08-01  4.470521
2021-09-01  4.614241
2021-10-01  5.224842
2021-11-01  5.851680
2021-12-01  6.145003
2022-01-01  6.486124
2022-02-01  6.801695
2022-03-01  7.900509
2022-04-01  8.518237
2022-05-01  8.855436
2022-06-01  9.249396
2022-07-01       NaN